config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  get '/', to: 'pages#home'

  # Sessions
  get '/login', to: 'sessions#new', as:'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # users
  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'patch'
  delete '/users/:id', to: 'users#destroy', as:'delete_user'

  #blog
  get '/blogs', to: 'blog#index', as: 'blogs'
  get '/blogs/new', to: 'blog#new'
  post '/blogs', to: 'blog#create', as: 'new_blog'
  get '/blogs/:id', to: 'blog#show', as: 'blog'
  get '/blogs/:id/edit', to: 'blog#edit', as: 'edit_blog'
  patch '/blogs/:id', to: 'blog#update'
  delete '/blogs/:id', to: 'blog#destroy', as: 'delete_blog'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
 belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue
    nil
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  # before_filter :authorize
  def index
    @blogs = Blog.all.order("created_at DESC")
  end

  def new
    @blog = Blog.new
    render :new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      flash[:notice] = "successfully created blog post"
      redirect_to user_path(current_user)
    else
      flash[:error] = "something went wrong"
      redirect_to blogs_path
    end
  end

  def show
    @blog = get_blog
  end

  def edit
    @blog = get_blog
  end

  def update
    @blog = get_blog
    @blog.update_attributes(blog_params)
    redirect_to user_path(current_user)
  end



  def destroy
    blog = get_blog
    blog.destroy
    redirect_to user_path(current_user)
  end

  private

  def blog_id
    params[:id]
  end

  def get_blog
    Blog.find_by_id(blog_id)
  end

  def blog_params
    params.require(:blog).permit(:title, :post, :user_id)

  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # before_filter :authorize
  def index
    @blogs = Blog.all.order("created_at DESC")
  end

  def new
    @blog = Blog.new
    render :new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      flash[:notice] = "successfully created blog post"
      redirect_to user_path(current_user)
    else
      flash[:error] = "something went wrong"
      redirect_to blogs_path
    end
  end

  def show
    @blog = get_blog
  end

  def edit
    @blog = get_blog
  end

  def update
    @blog = get_blog
    if @blog.update_attributes(blog_params)
      @status = "success";
    else
      @status = "error";
      @errors = @blog.errors.full_messages.join(', ')
    end
    respond_to {|format| format.js}
  end

  def destroy
    blog = get_blog
    blog.destroy
    redirect_to user_path(current_user)
  end

  private

  def blog_id
    params[:id]
  end

  def get_blog
    Blog.find_by_id(blog_id)
  end

  def blog_params
    params.require(:blog).permit(:title, :post, :user_id)

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to '/signup'
    end
  end

  def show
    @user = User.find(params[:id])
    @blogs = @user.blogs.all.order('created_at DESC')
    @blog = Blog.new()
    # redirect_to current_user if @user != current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.update_attributes(update_user_params)
    redirect_to user_path(@user.id)
  end


  private

  def update_user_params
    params.require(:user).permit(:name, :email, :username, :description)
  end

  def user_params
    params.require(:user).permit(:name, :email, :username, :description, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog/_edit.html.erb
<%= form_for @blog do |f| %>
    <% if @blog.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @blog.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="panel panel-default">
      <div class="panel-body">
          <%= f.label :title %>
          <br>
          <%= f.text_field :title, value: '@blog.title' %>
          <br>
          <%= f.label :post %>
          <br>
          <%= f.text_area :post, value: @blog.post %>
          <br>
          <%= f.hidden_field :user_id, value: current_user.id%>
      </div>
      <div class="panel-footer">
          <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
    <% if @blog.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @blog.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="panel panel-default">
      <div class="panel-body">
          <%= f.label :title %>
          <br>
          <%= f.text_field :title %>
          <br>
          <%= f.label :post %>
          <br>
          <%= f.text_area :post %>
          <br>
          <%= f.hidden_field :user_id, value: current_user.id%>
      </div>
      <div class="panel-footer">
          <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/blogs/edit.html.erb
<%= form_for @blog do |f| %>
    <% if @blog.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @blog.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <div class="panel panel-default">
      <div class="panel-body">
          <%= f.label :title %>
          <br>
          <%= f.text_field :title, value: @blog.title %>
          <br>
          <%= f.label :post %>
          <br>
          <%= f.text_area :post, value: @blog.post %>
          <br>
          <%= f.hidden_field :user_id, value: current_user.id%>
      </div>
      <div class="panel-footer">
          <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/blogs/index.html.erb
<div class='col-sm-6 col-md-offset-3'>
  <div class='post_container'>
    <h1>Blog posts</h1>

    <div class='panel panel-default'>
      <div class='panel-body'>
        <p>
          This blog was created! I hope you enjoy!</p>
      </div>
    </div>

  </div>

  <div class='post_container'>
    <% @blogs.each do |blog| %>
    <div class='panel panel-default'>
      <div class='panel-heading'><%= blog.user.username %></div>

      <div class='panel-body'>
        <h2><%= blog.title %></h2><hr/>
        <strong>Date Created:</strong>
        <%= blog.created_at.strftime("%B %-d, %Y") %>
        <p><%= blog.post %></p>

      </div>

    </div>
    <br>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class='col-md-6 col-md-offset-3 container'>

  <%= form_for @blog do |f| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      New Post
    </div>
    <div class="panel-body">
      <p>Title:
      </p><%= f.text_field :title %>
      <p>Post:
      </p><%= f.text_area :post %>
      <br>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit "Save Post", class: 'btn btn-success' %>
      <% end %>
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Philosophizer</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">philosphizer</a>
          <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Blog", "/blog" %></li>

            <% if current_user %>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Logout", '/logout' %></li>
          <% else %>
            <li><%= link_to "Login", '/login' %></li>
            <% end %>

          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<link href='https://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
<div class="jumbotron">
  <div class="jumbo_text">
    Je pense donc <br /> je philosophize
  </div>
</div>

<div class="container icons">


<a href="#"><i class="fa fa-envelope fa-4x"></i> </a>
<a href="#"><i class="fa fa-facebook-official fa-4x"></i> </a>
<a href="#"><i class="fa fa-twitter-square fa-4x"></i> </a>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

<div class="panel panel-default">
    <div class="panel-body">
        <%= f.label :name %>
        <br>
        <%= f.text_field :name %>
        <br>
        <%= f.label :username %>
        <br>
        <%= f.text_field :username %>
        <br>
        <%= f.label :email %>
        <br>
        <%= f.text_field :email %>
        <br>
        <%= f.label :description %>
        <br>
        <%= f.text_area :description %>
    </div>
    <div class="panel-footer">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
    </div>

app/views/users/new.html.erb
<div class='col-md-6 col-md-offset-3 container'>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>Signup!</h1>
    </div>
    <div class="panel-body">
      <%= form_for :user, url: '/users' do |f| %>
        <p>Name: <%= f.text_field :name %></p>
        <p>Email: <%= f.text_field :email %></p>
        <p>Username: <%= f.text_field :username %></p>
        <p>Password: <%= f.password_field :password %></p>
        <p>Password Confirmation: <%= f.password_field :password_confirmation %></p>
        <p><%= f.submit "Submit" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-md-6 col-md-offset-3 container">

  <div class='panel panel-default'>
    <div class="panel-heading">
      Profile
    </div>
    <div class="panel-body">
      <div class="col-md-3 profile">
        <img src='http://placehold.it/200x200&text=image+placeholder' />
      </div>
      <div class="col-md-6 col-md-offset-2 profile">
        <strong>Name:
        </strong>
        <%= current_user.name %>
        <br/>
        <strong>Email:</strong>
        <%= current_user.email %>
        <br/>
        <strong>Username:</strong>
        <%= current_user.username %>
        <br/>
        <strong>Date joined:</strong>
        <%= current_user.created_at.strftime("%B %-d, %Y") %>
        <hr />
        <strong>About me:</strong>
        <br />
        <%= current_user.description %>
      </div>
    </div>
    <div class="panel-footer">
      <!-- <%= link_to "New Post", '/blog/new', class: 'btn btn-info' %> -->
      <%= link_to "New Post", "#", class: 'btn btn-warning', 'data-target' => "#postModal_#{current_user.id}", 'data-toggle' => 'modal'  %>
      <%= link_to "Edit Profile", "#", class: 'btn btn-warning', 'data-target' => "#myModal_#{current_user.id}", 'data-toggle' => 'modal'  %>
    </div>
  </div>
</div>

<div class="modal fade" id='blogs-modal' role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="postModalLabel">New Post</h4>
      </div>
      <div class="modal-body">
        <%= render 'blogs/form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade" id='<%= "myModal_#{current_user.id}" %>' role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit Profile</h4>
      </div>
      <div class="modal-body">
        <%= render 'users/form', user: current_user %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="container">
  <div class='col-md-6 col-md-offset-3'>

    <% @blogs.each do |blog| %>
    <div class='panel panel-default' data-id='<%= blog.id %>'>
      <div class="panel-heading">
        <%= blog.created_at.strftime("%B %-d, %Y") %></div>

      <div class="panel-body">
        <strong>Title:</strong> <br>
        <p><%= blog.title %></p>
        <hr/>
        <strong>Post:</strong> <br>
        <p><%= blog.post %></p>
      </div>
      <div class="panel-footer">
<<<<<<< Updated upstream
        <%= button_to "Edit Post", edit_blog_path(blog.id), method: :get, class: "btn btn-warning" %>
=======

        <button type='button' class='edit-post btn btn-warning' data-id='<%= blog.id %>'
            data-toggle='modal' data-target='#blogs-modal'>
          Edit Post
        </button>

        <%#= button_to "Edit Post", edit_blog_path(blog.id), method: :get, class: "btn btn-warning" %>
>>>>>>> Stashed changes
        <%= button_to "Delete Post", delete_blog_path(blog.id), method: :get, class: "btn btn-warning" %>
      </div>
    </div>
    <% end %>
  </div>

</div>